name: Update JSON

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときにワークフローをトリガー

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update JSON
        run: |
          echo '{"message": "New message"}' > data.json
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data.json
          git commit -m "Update JSON [skip ci]"
          git push
